In [2]:
import numpy as np
import math

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) 
print(arr)

#array dimensions
print(arr.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
1


In [22]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]) 
print(arr)

# array dimensions
print(arr.ndim)
print(arr.shape)

print(arr.dtype)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
(4, 5)
int64


In [32]:
print(np.zeros((3,4)))
print('----')
print(np.ones((2,3)))
print('----')
# random array
print(np.random.rand(3,4))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
----
[[1. 1. 1.]
 [1. 1. 1.]]
----
[[0.13457995 0.51357812 0.18443987 0.78533515]
 [0.85397529 0.49423684 0.84656149 0.07964548]
 [0.50524609 0.0652865  0.42812233 0.09653092]]
